### ISSUE TITLE
Ваш пакет работает?

### ISSUE THREAD

**Issue by Sirgalas** [dimmduh/Parser-Kinopoisk#4]
Я так понимаю что нет как только не пробовал и так 
php composer.phar require "dimmduh/Parser-Kinopoisk:dev-master"
и так 
php composer.phar require "dimmduh/Parser-Kinopoisk@dev" тоже
на packagist его тоже нет есть только клон вашего пакета 
[https://packagist.org/packages/eadanilenko/kinopoisk-info](url)

**Comment by dimmduh** [comment]
Вы можете "установить" через композер, если указать откуда брать
http://stackoverflow.com/questions/12954051/use-php-composer-to-clone-git-repo

на packagist более актуальная версия, думаю

Оффтоп. Что то произошло в мире?) Почему резкий интерес 5 людей за последние 30 дней к парсеру кинопоиска?)

**Comment by Sirgalas** [comment]
Кинопоиск рубит парсеры

**Comment by dimmduh** [comment]
Прокси в помощь)

**Comment by Sirgalas** [comment]
вы считаете по прокси рубят. Мне кажется нет попытка получить даные с пяти разных ip все равно рубит

**Comment by dimmduh** [comment]
Тогда возможно заголовки не все шлются, юзер агент, авторизация.

**Comment by Sirgalas** [comment]
не у вас таже проблема к yii подключился вот ответ "HTTP/1.1 301 Moved Permanently"

**Comment by Romamo** [comment]
По http больше не отдает, только https.

**Comment by dimmduh** [comment]
ох, уж эти, поборники безопасного интернета

**Comment by Romamo** [comment]
Да, и пакет все же работает?
